In [18]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [20]:
# Reading Data

In [23]:
pecarn_data = pd.read_csv('TBI PUD 10-08-2013.csv', index_col=0)
pecarn_data.head()

,EmplType,Certification,InjuryMech,High_impact_InjSev,Amnesia_verb,LOCSeparate,LocLen,Seiz,SeizOccur,SeizLen,...,Finding20,Finding21,Finding22,Finding23,DeathTBI,HospHead,HospHeadPosCT,Intub24Head,Neurosurgery,PosIntFinal
PatNum,,,,,,,,,,,,,,,,,,,,,
1,3.0,3,11.0,2.0,0.0,0.0,92.0,0.0,92.0,92.0,...,92,92,92,92,0.0,0.0,0,0.0,0.0,0.0
2,5.0,3,8.0,2.0,0.0,0.0,92.0,0.0,92.0,92.0,...,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0
3,5.0,3,5.0,2.0,NaN,NaN,92.0,NaN,92.0,92.0,...,0,0,0,0,0.0,1.0,0,0.0,0.0,0.0
4,5.0,3,6.0,1.0,91.0,0.0,92.0,0.0,92.0,92.0,...,92,92,92,92,0.0,0.0,0,0.0,0.0,0.0
5,3.0,3,12.0,2.0,91.0,0.0,92.0,0.0,92.0,92.0,...,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0

In [ ]:
# Data Type

In [25]:
print(pecarn_data.dtypes)
pecarn_dataTypeFrame = pd.DataFrame(pecarn_data.dtypes)
pecarn_dataTypeFrame.to_csv (r'datatype.csv', index = False, header=True)

EmplType              float64
Certification           int64
InjuryMech            float64
High_impact_InjSev    float64
Amnesia_verb          float64
                       ...
HospHead              float64
HospHeadPosCT           int64
Intub24Head           float64
Neurosurgery          float64
PosIntFinal           float64
Length: 124, dtype: object

In [28]:
# Convert all data into INT64

In [34]:
pecarn_df = pd.DataFrame(pecarn_data)
pecarn_df = pecarn_df.astype(float).astype('Int64')
print(pecarn_df.dtypes)

EmplType              Int64
Certification         Int64
InjuryMech            Int64
High_impact_InjSev    Int64
Amnesia_verb          Int64
                      ...
HospHead              Int64
HospHeadPosCT         Int64
Intub24Head           Int64
Neurosurgery          Int64
PosIntFinal           Int64
Length: 124, dtype: object

In [36]:
pecarn_df.head(5)

,EmplType,Certification,InjuryMech,High_impact_InjSev,Amnesia_verb,LOCSeparate,LocLen,Seiz,SeizOccur,SeizLen,...,Finding20,Finding21,Finding22,Finding23,DeathTBI,HospHead,HospHeadPosCT,Intub24Head,Neurosurgery,PosIntFinal
PatNum,,,,,,,,,,,,,,,,,,,,,
1,3,3,11,2,0,0,92,0,92,92,...,92,92,92,92,0,0,0,0,0,0
2,5,3,8,2,0,0,92,0,92,92,...,0,0,0,0,0,0,0,0,0,0
3,5,3,5,2,NaN,NaN,92,NaN,92,92,...,0,0,0,0,0,1,0,0,0,0
4,5,3,6,1,91,0,92,0,92,92,...,92,92,92,92,0,0,0,0,0,0
5,3,3,12,2,91,0,92,0,92,92,...,0,0,0,0,0,0,0,0,0,0
6,3,3,NaN,NaN,91,0,92,0,92,92,...,92,92,92,92,0,0,0,0,0,0
7,3,3,7,1,0,0,92,0,92,92,...,92,92,92,92,0,0,0,0,0,0
8,3,3,12,2,0,0,92,0,92,92,...,92,92,92,92,0,0,0,0,0,0
9,5,3,6,1,91,0,92,0,92,92,...,92,92,92,92,0,0,0,0,0,0
10,5,3,8,2,91,0,92,0,92,92,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Counting NAN

In [42]:
count_nan = len(pecarn_df) - pecarn_df.count()
count_nan

EmplType                18
Certification            0
InjuryMech             301
High_impact_InjSev     334
Amnesia_verb          2296
                      ...
HospHead                 3
HospHeadPosCT            0
Intub24Head              4
Neurosurgery             1
PosIntFinal             20
Length: 124, dtype: int64

In [ ]:
# Converting all NAN to 92 - Not Sure if this is the right way to replace NAN

In [44]:
#pecarn_df = pecarn_df.fillna(92)

In [ ]:
# Group by GCSTotal and POSTIntFinal
### Note: GCSTotal =3-13 can be used in postive prediction and GSCTotal= 14,15 can used in Negative prediction

In [50]:
pecarn_df.groupby(['GCSTotal', 'PosIntFinal']).size()

GCSTotal  PosIntFinal
3         0                 51
          1                126
4         0                  1
          1                 21
5         0                  2
          1                 16
6         0                 21
          1                 28
7         0                 14
          1                 28
8         0                 22
          1                 24
9         0                 35
          1                 25
          92                 1
10        0                 32
          1                 22
11        0                 67
          1                 26
12        0                 81
          1                 21
13        0                254
          1                 50
          92                 1
14        0               1234
          1                107
          92                 3
15        0              40802
          1                269
          92                15
dtype: int64

In [ ]:
# Group by CTDone and POSTIntFinal
### Note: if CTDOne not condering in model then remove fields like EDCT, PosCT, Finding1 to Finding23

In [56]:
pecarn_df.groupby(['PosIntFinal','CTDone']).size()

PosIntFinal  CTDone  DeathTBI
0            0       0           27476
                     92              1
             1       0           15135
                     92              4
1            0       0               3
                     1              16
             1       0             694
                     1              50
92           0       0               3
                     92              1
             1       0              14
                     92              2
dtype: int64

In [ ]:
## The result here shows that 19 patients required a CT scan but it did performed
## Most importantly 15139 unnecesorry CT Scan was performed

In [59]:
pecarn_df.groupby(['PosIntFinal','CTDone','DeathTBI']).size()

PosIntFinal  CTDone  DeathTBI
0            0       0           27476
                     92              1
             1       0           15135
                     92              4
1            0       0               3
                     1              16
             1       0             694
                     1              50
92           0       0               3
                     92              1
             1       0              14
                     92              2
dtype: int64

In [ ]:
## The result above suggests that there are 16 death due to trauma who did not go throu CT Scan

In [ ]:
# Droping unncessory dataset - this needs to revised
## PosCT = finding 1 to 23, therefore findings are removed

In [ ]:
to_drop = ['EmplType',
           'Certification',
           'CTForm1',
           'AgeInMonth',
           'Finding1',
           'Finding2',
           'Finding3',
           'Finding4',
           'Finding5',
           'Finding6',
           'Finding7',
           'Finding8',
           'Finding9',
           'Finding10',
           'Finding11',
           'Finding12',
           'Finding13',
           'Finding14',
           'Finding20',
           'Finding21',
           'Finding22',
           'Finding23']
pecarn_df = pecarn_df.drop(to_drop, inplace=True, axis=1)

In [66]:
pecarn_df.head()

,InjuryMech,High_impact_InjSev,Amnesia_verb,LOCSeparate,LocLen,Seiz,SeizOccur,SeizLen,ActNorm,HA_verb,...,EDDisposition,CTDone,EDCT,PosCT,DeathTBI,HospHead,HospHeadPosCT,Intub24Head,Neurosurgery,PosIntFinal
PatNum,,,,,,,,,,,,,,,,,,,,,
1,11,2,0,0,92,0,92,92,1,1,...,1,0,92,92,0,0,0,0,0,0
2,8,2,0,0,92,0,92,92,1,0,...,1,1,1,0,0,0,0,0,0,0
3,5,2,92,92,92,92,92,92,0,92,...,5,1,1,0,0,1,0,0,0,0
4,6,1,91,0,92,0,92,92,1,91,...,1,0,92,92,0,0,0,0,0,0
5,12,2,91,0,92,0,92,92,0,91,...,1,1,1,0,0,0,0,0,0,0